resolver: lts-14.14

packages:
  - demo

extra-deps:
  # to use a version of Hadui & Haze from github
  # - url: https://github.com/complyue/hadui/archive/0.1.0.2.tar.gz
  #   subdirs:
  #     - hadui
  # - url: https://github.com/complyue/haze/archive/0.1.0.rc0.tar.gz
  #   subdirs:
  #     - haze

extra-deps:
  # to use the version of Hadui & Haze checked out locally
  - ../hadui/hadui
  - ../haze/haze

# Stack's Nix integration is incompatible with Hadui,
# let stack run in `nix-shell` with Nix provided GHC
system-ghc: true
nix:
  enable: false
