name: haze-demo
version: 0.1.0.0
github: complyue/haze-demo
license: BSD3
author: Compl Yue
maintainer: compl.yue@icloud.com
copyright: 2019 Compl Yue

extra-source-files:
  - README.md

synopsis: demo for Haze
category: Visualization

description: Please see the README on Github at <https://github.com/complyue/haze>

dependencies:
  - base
  - rio

  - hadui
  - haze

ghc-options:
  - -Wall

library:
  source-dirs: src
